language: python
dist: trusty

python:
  - 2.7
env:
  - SDL_VIDEODRIVER="dummy" SDL_AUDIODRIVER="dummy"
virtualenv:
  system_site_package: true
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run -m unittest discover test/
after_success:
  - coveralls
notifications:
  on_success: never
  on_failure: always
